# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "GainForest Maps"
  port = 8915
  apiUrl = "/api"
   includeEnvironmentVariables = ['REDISHOST', 'REDISPASSWORD', 'REDISPORT', 'GAINFOREST_WALLETS', 'BITQUERY_API_KEY', 'MAPBOXGL_ACCESSTOKEN', 'AWS_STORAGE', 'NICFI_API_KEY', 'AUTH0_DOMAIN', 'AUTH0_CLIENT_ID', 'AUTH0_REDIRECT_URI', 'AUTH0_AUDIENCE', 'GAINFOREST_ENDPOINT'] # any ENV vars that should be available to the web side, see https://redwoodjs.com/docs/environment-variables#web
[api]
  port = 8916
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
