import React, { useState, useEffect } from 'react'

import { CircleHelp, FileText } from 'lucide-react'
import { useSelector } from 'react-redux'
import { Tooltip } from 'react-tooltip'
import styled from 'styled-components'

import { toKebabCase } from 'src/utils/toKebabCase'

const PDF_FILES = ['canopy_sizes.pdf', 'umap_projections.pdf']

const IFRAME_OPTIONS = [
  {
    value: 'https://andrewcottam.github.io/web_apps/mapboxGL/finals.html',
    label: 'Canopy Map',
  },
  {
    value:
      'https://andrewcottam.github.io/web_apps/mapboxGL/anarcardium_spruceanum.html',
    label: 'Anarcardium Spruceanum',
  },
  {
    value:
      'https://andrewcottam.github.io/web_apps/mapboxGL/attalea_maripa.html',
    label: 'Attalea Maripa',
  },
  {
    value:
      'https://andrewcottam.github.io/web_apps/openlayers/label_crowns/dist/index.html',
    label: 'Labeling Tool',
  },
]

interface PdfStatus {
  filename: string
  exists: boolean
}

interface Iframe {
  value: string
  label: string
}

export const CanopyInsights = () => {
  const [pdfStatuses, setPdfStatuses] = useState<PdfStatus[]>([])
  const kebabCasedProjectName = useSelector((state: any) =>
    toKebabCase(state.project.name)
  )
  const [iframeOptions, setIframeOptions] = useState<Iframe[]>([])
  const [selectedIframe, setSelectedIframe] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (kebabCasedProjectName) {
      Promise.all(
        PDF_FILES.map((file) =>
          fetch(
            `${process.env.AWS_STORAGE}/canopy/${kebabCasedProjectName}/${file}`
          )
            .then((response) => ({ filename: file, exists: response.ok }))
            .catch(() => ({ filename: file, exists: false }))
        )
      ).then(setPdfStatuses)
    }
  }, [kebabCasedProjectName])

  useEffect(() => {
    if (kebabCasedProjectName == 'xprize-rainforest-finals') {
      setIframeOptions(IFRAME_OPTIONS)
      setSelectedIframe(IFRAME_OPTIONS[0].value)
    }
    setLoading(false)
  }, [kebabCasedProjectName])

  if (!kebabCasedProjectName) {
    return <Container>Loading Canopy analysis insights...</Container>
  }

  const availablePdfs = pdfStatuses.filter((status) => status.exists)

  const handleIframeChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedIframe(event.target.value)
  }

  if (loading) {
    return (
      <Container>
        <p>Loading...</p>
      </Container>
    )
  }

  if (availablePdfs?.length == 0 && iframeOptions?.length == 0) {
    return (
      <Container>
        <p>No canopy data found.</p>
      </Container>
    )
  }

  return (
    <Container>
      <h2>Canopy Analysis Insights</h2>
      <p>
        <CircleHelp color="#65962A" size={14} data-tooltip-id={`cherty`} />
        This insight was generated by passing in the drone orthomosaic files
        through the bioclip-canopy huggingface model.
      </p>
      <Tooltip
        id={`cherty`}
        delayShow={10}
        style={{ zIndex: 1000 }}
        place={'right'}
      >
        <img
          alt="Cherty: Canopy Analysis"
          style={{ maxWidth: '600px', maxHeight: '600px' }}
          src={`${process.env.AWS_STORAGE}/cherty/canopy-analysis-cherted.svg`}
        />
      </Tooltip>
      <MapContainer>
        <h3>Interactive Map</h3>
        <SelectContainer>
          <label htmlFor="iframe-select">Select View:</label>
          <select
            id="iframe-select"
            value={selectedIframe}
            onChange={handleIframeChange}
          >
            {iframeOptions.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </SelectContainer>
        <iframe
          src={selectedIframe}
          title="Selected View"
          width="100%"
          height="500px"
          frameBorder="0"
        />
      </MapContainer>
      <h3>Canopy Analysis Plots</h3>
      {availablePdfs.length > 0 ? (
        <PdfContainer>
          {availablePdfs.map(({ filename }) => (
            <PdfItem key={filename}>
              <iframe
                src={`${process.env.AWS_STORAGE}/canopy/${kebabCasedProjectName}/${filename}`}
                width="100%"
                height="500px"
                title={filename}
              />
              <a
                href={`${process.env.AWS_STORAGE}/canopy/${kebabCasedProjectName}/${filename}`}
                target="_blank"
                rel="noopener noreferrer"
              >
                Open {filename.replace('_', ' ').replace('.pdf', '')}
              </a>
            </PdfItem>
          ))}
        </PdfContainer>
      ) : (
        <PlaceholderContainer>
          <FileText size={48} />
          <p>No Canopy analysis plots are available yet. Check back later!</p>
        </PlaceholderContainer>
      )}
    </Container>
  )
}

const Container = styled.div`
  margin: 16px 0px;
`

const MapContainer = styled.div`
  margin-bottom: 24px;
  border: 1px solid #ddd;
  border-radius: 4px;
  overflow: hidden;

  h3 {
    padding: 12px;
    margin: 0;
    background-color: #f0f0f0;
  }

  iframe {
    border: none;
  }
`

const SelectContainer = styled.div`
  display: flex;
  align-items: center;
  padding: 12px;
  background-color: #f0f0f0;

  label {
    margin-right: 8px;
    font-weight: bold;
  }

  select {
    padding: 4px 8px;
    border-radius: 4px;
    border: 1px solid #ddd;
  }
`

const PdfContainer = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 16px;
  margin-top: 16px;
`

const PdfItem = styled.div`
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  text-align: center;

  iframe {
    border: none;
    margin-bottom: 8px;
  }

  a {
    color: #0066cc;
    text-decoration: none;
    &:hover {
      text-decoration: underline;
    }
  }
`

const PlaceholderContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 32px;
  background-color: #f5f5f5;
  border-radius: 8px;
  text-align: center;

  svg {
    margin-bottom: 16px;
    color: #999;
  }

  p {
    color: #666;
    font-size: 18px;
  }
`
